name: Testing out github actions
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: 'https://github.com/bgarlow/snyk-github.git'
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: run the test python
      run: python test.py
      env:
        WORKING_DIR: ./snyk-github